#include "RegularField.h"

#include "RegularJF12.h"
#include "Jaffe.h"
#include "Helix.h"
#include "Uniform.h"
#include "Pshirkov.h"
#include "Archimedes.h"
#include "Sun.h"
#include "Han.h"
#include "TF17.h"
#include "TinyakovTkachev.h"
#include "HarariMollerachRoulet.h"

#include "YMW.h"