from _ImagineModels import MagneticField, RegularMagneticField, JF12MagneticField

from .HelperFunctions.CoordinateConversions import cyl2cart

from .MagneticFields.RegularMagneticFields import AxiSymmetricSpiral